# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='login.proto',
  package='LOGIN',
  serialized_pb='\n\x0blogin.proto\x12\x05LOGIN\"I\n\tlogin_req\x12\x0c\n\x04type\x18\x01 \x02(\x05\x12\x12\n\nservername\x18\x02 \x02(\t\x12\x0c\n\x04user\x18\x03 \x02(\t\x12\x0c\n\x04pass\x18\x04 \x02(\t\"\x18\n\tlogin_rsp\x12\x0b\n\x03ret\x18\x01 \x02(\x05')




_LOGIN_REQ = _descriptor.Descriptor(
  name='login_req',
  full_name='LOGIN.login_req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='LOGIN.login_req.type', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='servername', full_name='LOGIN.login_req.servername', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user', full_name='LOGIN.login_req.user', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pass', full_name='LOGIN.login_req.pass', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=22,
  serialized_end=95,
)


_LOGIN_RSP = _descriptor.Descriptor(
  name='login_rsp',
  full_name='LOGIN.login_rsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='LOGIN.login_rsp.ret', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=97,
  serialized_end=121,
)

DESCRIPTOR.message_types_by_name['login_req'] = _LOGIN_REQ
DESCRIPTOR.message_types_by_name['login_rsp'] = _LOGIN_RSP

class login_req(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOGIN_REQ

  # @@protoc_insertion_point(class_scope:LOGIN.login_req)

class login_rsp(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOGIN_RSP

  # @@protoc_insertion_point(class_scope:LOGIN.login_rsp)


# @@protoc_insertion_point(module_scope)
