# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pay.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pay.proto',
  package='PAY',
  serialized_pb='\n\tpay.proto\x12\x03PAY\"\x91\x01\n\x12PAY2Z_PlayerPayReq\x12\x0f\n\x07user_id\x18\x01 \x02(\r\x12\x0e\n\x06pay_id\x18\x02 \x02(\x0c\x12\x0e\n\x06marble\x18\x03 \x02(\r\x12\x11\n\trealcount\x18\x04 \x02(\r\x12\x0b\n\x03rmb\x18\x05 \x02(\r\x12\x16\n\x0eyouai_paysvrid\x18\x06 \x01(\r\x12\x12\n\nextra_data\x18\x07 \x01(\t\"z\n\x12Z2PAY_PlayerPayRsp\x12\x0f\n\x07user_id\x18\x01 \x02(\r\x12\x0b\n\x03ret\x18\x02 \x02(\x05\x12\x0e\n\x06\x65rrmsg\x18\x03 \x01(\x0c\x12\x0e\n\x06marble\x18\x04 \x01(\r\x12\x0e\n\x06pay_id\x18\x05 \x01(\x0c\x12\x16\n\x0eyouai_paysvrid\x18\x06 \x01(\r\"?\n\x10Z2C_PayResultRsp\x12\x0b\n\x03ret\x18\x01 \x02(\x05\x12\x0e\n\x06\x65rrmsg\x18\x02 \x01(\x0c\x12\x0e\n\x06marble\x18\x03 \x01(\r')




_PAY2Z_PLAYERPAYREQ = _descriptor.Descriptor(
  name='PAY2Z_PlayerPayReq',
  full_name='PAY.PAY2Z_PlayerPayReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='PAY.PAY2Z_PlayerPayReq.user_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pay_id', full_name='PAY.PAY2Z_PlayerPayReq.pay_id', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='marble', full_name='PAY.PAY2Z_PlayerPayReq.marble', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='realcount', full_name='PAY.PAY2Z_PlayerPayReq.realcount', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rmb', full_name='PAY.PAY2Z_PlayerPayReq.rmb', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='youai_paysvrid', full_name='PAY.PAY2Z_PlayerPayReq.youai_paysvrid', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='extra_data', full_name='PAY.PAY2Z_PlayerPayReq.extra_data', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=19,
  serialized_end=164,
)


_Z2PAY_PLAYERPAYRSP = _descriptor.Descriptor(
  name='Z2PAY_PlayerPayRsp',
  full_name='PAY.Z2PAY_PlayerPayRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='PAY.Z2PAY_PlayerPayRsp.user_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ret', full_name='PAY.Z2PAY_PlayerPayRsp.ret', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='errmsg', full_name='PAY.Z2PAY_PlayerPayRsp.errmsg', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='marble', full_name='PAY.Z2PAY_PlayerPayRsp.marble', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pay_id', full_name='PAY.Z2PAY_PlayerPayRsp.pay_id', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='youai_paysvrid', full_name='PAY.Z2PAY_PlayerPayRsp.youai_paysvrid', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=166,
  serialized_end=288,
)


_Z2C_PAYRESULTRSP = _descriptor.Descriptor(
  name='Z2C_PayResultRsp',
  full_name='PAY.Z2C_PayResultRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='PAY.Z2C_PayResultRsp.ret', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='errmsg', full_name='PAY.Z2C_PayResultRsp.errmsg', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='marble', full_name='PAY.Z2C_PayResultRsp.marble', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=290,
  serialized_end=353,
)

DESCRIPTOR.message_types_by_name['PAY2Z_PlayerPayReq'] = _PAY2Z_PLAYERPAYREQ
DESCRIPTOR.message_types_by_name['Z2PAY_PlayerPayRsp'] = _Z2PAY_PLAYERPAYRSP
DESCRIPTOR.message_types_by_name['Z2C_PayResultRsp'] = _Z2C_PAYRESULTRSP

class PAY2Z_PlayerPayReq(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PAY2Z_PLAYERPAYREQ

  # @@protoc_insertion_point(class_scope:PAY.PAY2Z_PlayerPayReq)

class Z2PAY_PlayerPayRsp(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _Z2PAY_PLAYERPAYRSP

  # @@protoc_insertion_point(class_scope:PAY.Z2PAY_PlayerPayRsp)

class Z2C_PayResultRsp(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _Z2C_PAYRESULTRSP

  # @@protoc_insertion_point(class_scope:PAY.Z2C_PayResultRsp)


# @@protoc_insertion_point(module_scope)
