# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rcminfo.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rcminfo.proto',
  package='rcm',
  serialized_pb='\n\rrcminfo.proto\x12\x03rcm\"\xe8\x01\n\x07RCMInfo\x12\x0f\n\x07role_id\x18\x01 \x01(\r\x12\x0c\n\x04\x66lag\x18\x02 \x01(\r\x12\x0e\n\x06status\x18\x03 \x01(\x05\x12\x11\n\tsync_time\x18\x04 \x01(\x04\x12\x11\n\tnick_name\x18\x05 \x01(\x0c\x12\r\n\x05level\x18\x06 \x01(\r\x12\x11\n\tgold_coin\x18\x07 \x01(\r\x12\x0e\n\x06marble\x18\x08 \x01(\r\x12\x15\n\rzonesvr_busid\x18\t \x01(\r\x12\x15\n\rgamesvr_busid\x18\n \x01(\r\x12\x13\n\x0broom_number\x18\x0b \x01(\r\x12\x13\n\x0bseat_number\x18\x0c \x01(\r\"$\n\x11RCMInfoGetRequest\x12\x0f\n\x07role_id\x18\x01 \x03(\r\"3\n\x12RCMInfoGetResponse\x12\x1d\n\x07rcminfo\x18\x01 \x03(\x0b\x32\x0c.rcm.RCMInfo\"\x89\x01\n\x14RCMInfoUpdateRequest\x12\x0c\n\x04\x66lag\x18\x01 \x01(\r\x12\x1d\n\x07rcminfo\x18\x02 \x01(\x0b\x32\x0c.rcm.RCMInfo\"D\n\x0eInfoUpdateFlag\x12\x10\n\x0c\x42\x61seDataInfo\x10\x01\x12\x0e\n\nOnlineInfo\x10\x02\x12\x10\n\x0cJoinGameInfo\x10\x04\"5\n\x15RCMInfoUpdateResponse\x12\x0f\n\x07role_id\x18\x01 \x01(\r\x12\x0b\n\x03ret\x18\x02 \x01(\x05\"2\n\x11RCMInfoSyncPlayer\x12\x1d\n\x07rcminfo\x18\x01 \x03(\x0b\x32\x0c.rcm.RCMInfo\" \n\rRCMInfoDelReq\x12\x0f\n\x07role_id\x18\x01 \x01(\r\"-\n\rRCMInfoDelRsp\x12\x0f\n\x07role_id\x18\x01 \x01(\r\x12\x0b\n\x03ret\x18\x02 \x01(\x05')



_RCMINFOUPDATEREQUEST_INFOUPDATEFLAG = _descriptor.EnumDescriptor(
  name='InfoUpdateFlag',
  full_name='rcm.RCMInfoUpdateRequest.InfoUpdateFlag',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BaseDataInfo', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OnlineInfo', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='JoinGameInfo', index=2, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=418,
  serialized_end=486,
)


_RCMINFO = _descriptor.Descriptor(
  name='RCMInfo',
  full_name='rcm.RCMInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='role_id', full_name='rcm.RCMInfo.role_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='flag', full_name='rcm.RCMInfo.flag', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='rcm.RCMInfo.status', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sync_time', full_name='rcm.RCMInfo.sync_time', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nick_name', full_name='rcm.RCMInfo.nick_name', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='level', full_name='rcm.RCMInfo.level', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gold_coin', full_name='rcm.RCMInfo.gold_coin', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='marble', full_name='rcm.RCMInfo.marble', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='zonesvr_busid', full_name='rcm.RCMInfo.zonesvr_busid', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gamesvr_busid', full_name='rcm.RCMInfo.gamesvr_busid', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='room_number', full_name='rcm.RCMInfo.room_number', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seat_number', full_name='rcm.RCMInfo.seat_number', index=11,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=23,
  serialized_end=255,
)


_RCMINFOGETREQUEST = _descriptor.Descriptor(
  name='RCMInfoGetRequest',
  full_name='rcm.RCMInfoGetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='role_id', full_name='rcm.RCMInfoGetRequest.role_id', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=257,
  serialized_end=293,
)


_RCMINFOGETRESPONSE = _descriptor.Descriptor(
  name='RCMInfoGetResponse',
  full_name='rcm.RCMInfoGetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rcminfo', full_name='rcm.RCMInfoGetResponse.rcminfo', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=295,
  serialized_end=346,
)


_RCMINFOUPDATEREQUEST = _descriptor.Descriptor(
  name='RCMInfoUpdateRequest',
  full_name='rcm.RCMInfoUpdateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='flag', full_name='rcm.RCMInfoUpdateRequest.flag', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rcminfo', full_name='rcm.RCMInfoUpdateRequest.rcminfo', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RCMINFOUPDATEREQUEST_INFOUPDATEFLAG,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=349,
  serialized_end=486,
)


_RCMINFOUPDATERESPONSE = _descriptor.Descriptor(
  name='RCMInfoUpdateResponse',
  full_name='rcm.RCMInfoUpdateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='role_id', full_name='rcm.RCMInfoUpdateResponse.role_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ret', full_name='rcm.RCMInfoUpdateResponse.ret', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=488,
  serialized_end=541,
)


_RCMINFOSYNCPLAYER = _descriptor.Descriptor(
  name='RCMInfoSyncPlayer',
  full_name='rcm.RCMInfoSyncPlayer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rcminfo', full_name='rcm.RCMInfoSyncPlayer.rcminfo', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=543,
  serialized_end=593,
)


_RCMINFODELREQ = _descriptor.Descriptor(
  name='RCMInfoDelReq',
  full_name='rcm.RCMInfoDelReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='role_id', full_name='rcm.RCMInfoDelReq.role_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=595,
  serialized_end=627,
)


_RCMINFODELRSP = _descriptor.Descriptor(
  name='RCMInfoDelRsp',
  full_name='rcm.RCMInfoDelRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='role_id', full_name='rcm.RCMInfoDelRsp.role_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ret', full_name='rcm.RCMInfoDelRsp.ret', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=629,
  serialized_end=674,
)

_RCMINFOGETRESPONSE.fields_by_name['rcminfo'].message_type = _RCMINFO
_RCMINFOUPDATEREQUEST.fields_by_name['rcminfo'].message_type = _RCMINFO
_RCMINFOUPDATEREQUEST_INFOUPDATEFLAG.containing_type = _RCMINFOUPDATEREQUEST;
_RCMINFOSYNCPLAYER.fields_by_name['rcminfo'].message_type = _RCMINFO
DESCRIPTOR.message_types_by_name['RCMInfo'] = _RCMINFO
DESCRIPTOR.message_types_by_name['RCMInfoGetRequest'] = _RCMINFOGETREQUEST
DESCRIPTOR.message_types_by_name['RCMInfoGetResponse'] = _RCMINFOGETRESPONSE
DESCRIPTOR.message_types_by_name['RCMInfoUpdateRequest'] = _RCMINFOUPDATEREQUEST
DESCRIPTOR.message_types_by_name['RCMInfoUpdateResponse'] = _RCMINFOUPDATERESPONSE
DESCRIPTOR.message_types_by_name['RCMInfoSyncPlayer'] = _RCMINFOSYNCPLAYER
DESCRIPTOR.message_types_by_name['RCMInfoDelReq'] = _RCMINFODELREQ
DESCRIPTOR.message_types_by_name['RCMInfoDelRsp'] = _RCMINFODELRSP

class RCMInfo(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RCMINFO

  # @@protoc_insertion_point(class_scope:rcm.RCMInfo)

class RCMInfoGetRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RCMINFOGETREQUEST

  # @@protoc_insertion_point(class_scope:rcm.RCMInfoGetRequest)

class RCMInfoGetResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RCMINFOGETRESPONSE

  # @@protoc_insertion_point(class_scope:rcm.RCMInfoGetResponse)

class RCMInfoUpdateRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RCMINFOUPDATEREQUEST

  # @@protoc_insertion_point(class_scope:rcm.RCMInfoUpdateRequest)

class RCMInfoUpdateResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RCMINFOUPDATERESPONSE

  # @@protoc_insertion_point(class_scope:rcm.RCMInfoUpdateResponse)

class RCMInfoSyncPlayer(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RCMINFOSYNCPLAYER

  # @@protoc_insertion_point(class_scope:rcm.RCMInfoSyncPlayer)

class RCMInfoDelReq(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RCMINFODELREQ

  # @@protoc_insertion_point(class_scope:rcm.RCMInfoDelReq)

class RCMInfoDelRsp(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RCMINFODELRSP

  # @@protoc_insertion_point(class_scope:rcm.RCMInfoDelRsp)


# @@protoc_insertion_point(module_scope)
