// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gameshop.proto

#ifndef PROTOBUF_gameshop_2eproto__INCLUDED
#define PROTOBUF_gameshop_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "db_cache.pb.h"
// @@protoc_insertion_point(includes)

namespace GAMESHOP {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_gameshop_2eproto();
void protobuf_AssignDesc_gameshop_2eproto();
void protobuf_ShutdownFile_gameshop_2eproto();

class C2S_Buy_Goods_Req;
class S2C_Buy_Goods_Rsp;
class C2S_Present_Goods_Req;
class S2C_Present_Goods_Rsp;

// ===================================================================

class C2S_Buy_Goods_Req : public ::google::protobuf::Message {
 public:
  C2S_Buy_Goods_Req();
  virtual ~C2S_Buy_Goods_Req();

  C2S_Buy_Goods_Req(const C2S_Buy_Goods_Req& from);

  inline C2S_Buy_Goods_Req& operator=(const C2S_Buy_Goods_Req& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const C2S_Buy_Goods_Req& default_instance();

  void Swap(C2S_Buy_Goods_Req* other);

  // implements Message ----------------------------------------------

  C2S_Buy_Goods_Req* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const C2S_Buy_Goods_Req& from);
  void MergeFrom(const C2S_Buy_Goods_Req& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 goods_id = 1;
  inline bool has_goods_id() const;
  inline void clear_goods_id();
  static const int kGoodsIdFieldNumber = 1;
  inline ::google::protobuf::int32 goods_id() const;
  inline void set_goods_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:GAMESHOP.C2S_Buy_Goods_Req)
 private:
  inline void set_has_goods_id();
  inline void clear_has_goods_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 goods_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_gameshop_2eproto();
  friend void protobuf_AssignDesc_gameshop_2eproto();
  friend void protobuf_ShutdownFile_gameshop_2eproto();

  void InitAsDefaultInstance();
  static C2S_Buy_Goods_Req* default_instance_;
};
// -------------------------------------------------------------------

class S2C_Buy_Goods_Rsp : public ::google::protobuf::Message {
 public:
  S2C_Buy_Goods_Rsp();
  virtual ~S2C_Buy_Goods_Rsp();

  S2C_Buy_Goods_Rsp(const S2C_Buy_Goods_Rsp& from);

  inline S2C_Buy_Goods_Rsp& operator=(const S2C_Buy_Goods_Rsp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const S2C_Buy_Goods_Rsp& default_instance();

  void Swap(S2C_Buy_Goods_Rsp* other);

  // implements Message ----------------------------------------------

  S2C_Buy_Goods_Rsp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const S2C_Buy_Goods_Rsp& from);
  void MergeFrom(const S2C_Buy_Goods_Rsp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 ret = 1;
  inline bool has_ret() const;
  inline void clear_ret();
  static const int kRetFieldNumber = 1;
  inline ::google::protobuf::int32 ret() const;
  inline void set_ret(::google::protobuf::int32 value);

  // optional int32 cost_money = 2;
  inline bool has_cost_money() const;
  inline void clear_cost_money();
  static const int kCostMoneyFieldNumber = 2;
  inline ::google::protobuf::int32 cost_money() const;
  inline void set_cost_money(::google::protobuf::int32 value);

  // optional int32 cost_marbel = 3;
  inline bool has_cost_marbel() const;
  inline void clear_cost_marbel();
  static const int kCostMarbelFieldNumber = 3;
  inline ::google::protobuf::int32 cost_marbel() const;
  inline void set_cost_marbel(::google::protobuf::int32 value);

  // optional int32 cost_goldcoin = 4;
  inline bool has_cost_goldcoin() const;
  inline void clear_cost_goldcoin();
  static const int kCostGoldcoinFieldNumber = 4;
  inline ::google::protobuf::int32 cost_goldcoin() const;
  inline void set_cost_goldcoin(::google::protobuf::int32 value);

  // repeated .DBCACHE.Prop gain_prop = 5;
  inline int gain_prop_size() const;
  inline void clear_gain_prop();
  static const int kGainPropFieldNumber = 5;
  inline const ::DBCACHE::Prop& gain_prop(int index) const;
  inline ::DBCACHE::Prop* mutable_gain_prop(int index);
  inline ::DBCACHE::Prop* add_gain_prop();
  inline const ::google::protobuf::RepeatedPtrField< ::DBCACHE::Prop >&
      gain_prop() const;
  inline ::google::protobuf::RepeatedPtrField< ::DBCACHE::Prop >*
      mutable_gain_prop();

  // @@protoc_insertion_point(class_scope:GAMESHOP.S2C_Buy_Goods_Rsp)
 private:
  inline void set_has_ret();
  inline void clear_has_ret();
  inline void set_has_cost_money();
  inline void clear_has_cost_money();
  inline void set_has_cost_marbel();
  inline void clear_has_cost_marbel();
  inline void set_has_cost_goldcoin();
  inline void clear_has_cost_goldcoin();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 ret_;
  ::google::protobuf::int32 cost_money_;
  ::google::protobuf::int32 cost_marbel_;
  ::google::protobuf::int32 cost_goldcoin_;
  ::google::protobuf::RepeatedPtrField< ::DBCACHE::Prop > gain_prop_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];

  friend void  protobuf_AddDesc_gameshop_2eproto();
  friend void protobuf_AssignDesc_gameshop_2eproto();
  friend void protobuf_ShutdownFile_gameshop_2eproto();

  void InitAsDefaultInstance();
  static S2C_Buy_Goods_Rsp* default_instance_;
};
// -------------------------------------------------------------------

class C2S_Present_Goods_Req : public ::google::protobuf::Message {
 public:
  C2S_Present_Goods_Req();
  virtual ~C2S_Present_Goods_Req();

  C2S_Present_Goods_Req(const C2S_Present_Goods_Req& from);

  inline C2S_Present_Goods_Req& operator=(const C2S_Present_Goods_Req& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const C2S_Present_Goods_Req& default_instance();

  void Swap(C2S_Present_Goods_Req* other);

  // implements Message ----------------------------------------------

  C2S_Present_Goods_Req* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const C2S_Present_Goods_Req& from);
  void MergeFrom(const C2S_Present_Goods_Req& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 goods_id = 1;
  inline bool has_goods_id() const;
  inline void clear_goods_id();
  static const int kGoodsIdFieldNumber = 1;
  inline ::google::protobuf::int32 goods_id() const;
  inline void set_goods_id(::google::protobuf::int32 value);

  // repeated int32 receiver_id = 2;
  inline int receiver_id_size() const;
  inline void clear_receiver_id();
  static const int kReceiverIdFieldNumber = 2;
  inline ::google::protobuf::int32 receiver_id(int index) const;
  inline void set_receiver_id(int index, ::google::protobuf::int32 value);
  inline void add_receiver_id(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      receiver_id() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_receiver_id();

  // @@protoc_insertion_point(class_scope:GAMESHOP.C2S_Present_Goods_Req)
 private:
  inline void set_has_goods_id();
  inline void clear_has_goods_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > receiver_id_;
  ::google::protobuf::int32 goods_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_gameshop_2eproto();
  friend void protobuf_AssignDesc_gameshop_2eproto();
  friend void protobuf_ShutdownFile_gameshop_2eproto();

  void InitAsDefaultInstance();
  static C2S_Present_Goods_Req* default_instance_;
};
// -------------------------------------------------------------------

class S2C_Present_Goods_Rsp : public ::google::protobuf::Message {
 public:
  S2C_Present_Goods_Rsp();
  virtual ~S2C_Present_Goods_Rsp();

  S2C_Present_Goods_Rsp(const S2C_Present_Goods_Rsp& from);

  inline S2C_Present_Goods_Rsp& operator=(const S2C_Present_Goods_Rsp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const S2C_Present_Goods_Rsp& default_instance();

  void Swap(S2C_Present_Goods_Rsp* other);

  // implements Message ----------------------------------------------

  S2C_Present_Goods_Rsp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const S2C_Present_Goods_Rsp& from);
  void MergeFrom(const S2C_Present_Goods_Rsp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 ret_code = 1;
  inline bool has_ret_code() const;
  inline void clear_ret_code();
  static const int kRetCodeFieldNumber = 1;
  inline ::google::protobuf::int32 ret_code() const;
  inline void set_ret_code(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:GAMESHOP.S2C_Present_Goods_Rsp)
 private:
  inline void set_has_ret_code();
  inline void clear_has_ret_code();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 ret_code_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_gameshop_2eproto();
  friend void protobuf_AssignDesc_gameshop_2eproto();
  friend void protobuf_ShutdownFile_gameshop_2eproto();

  void InitAsDefaultInstance();
  static S2C_Present_Goods_Rsp* default_instance_;
};
// ===================================================================


// ===================================================================

// C2S_Buy_Goods_Req

// required int32 goods_id = 1;
inline bool C2S_Buy_Goods_Req::has_goods_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void C2S_Buy_Goods_Req::set_has_goods_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void C2S_Buy_Goods_Req::clear_has_goods_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void C2S_Buy_Goods_Req::clear_goods_id() {
  goods_id_ = 0;
  clear_has_goods_id();
}
inline ::google::protobuf::int32 C2S_Buy_Goods_Req::goods_id() const {
  return goods_id_;
}
inline void C2S_Buy_Goods_Req::set_goods_id(::google::protobuf::int32 value) {
  set_has_goods_id();
  goods_id_ = value;
}

// -------------------------------------------------------------------

// S2C_Buy_Goods_Rsp

// required int32 ret = 1;
inline bool S2C_Buy_Goods_Rsp::has_ret() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void S2C_Buy_Goods_Rsp::set_has_ret() {
  _has_bits_[0] |= 0x00000001u;
}
inline void S2C_Buy_Goods_Rsp::clear_has_ret() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void S2C_Buy_Goods_Rsp::clear_ret() {
  ret_ = 0;
  clear_has_ret();
}
inline ::google::protobuf::int32 S2C_Buy_Goods_Rsp::ret() const {
  return ret_;
}
inline void S2C_Buy_Goods_Rsp::set_ret(::google::protobuf::int32 value) {
  set_has_ret();
  ret_ = value;
}

// optional int32 cost_money = 2;
inline bool S2C_Buy_Goods_Rsp::has_cost_money() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void S2C_Buy_Goods_Rsp::set_has_cost_money() {
  _has_bits_[0] |= 0x00000002u;
}
inline void S2C_Buy_Goods_Rsp::clear_has_cost_money() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void S2C_Buy_Goods_Rsp::clear_cost_money() {
  cost_money_ = 0;
  clear_has_cost_money();
}
inline ::google::protobuf::int32 S2C_Buy_Goods_Rsp::cost_money() const {
  return cost_money_;
}
inline void S2C_Buy_Goods_Rsp::set_cost_money(::google::protobuf::int32 value) {
  set_has_cost_money();
  cost_money_ = value;
}

// optional int32 cost_marbel = 3;
inline bool S2C_Buy_Goods_Rsp::has_cost_marbel() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void S2C_Buy_Goods_Rsp::set_has_cost_marbel() {
  _has_bits_[0] |= 0x00000004u;
}
inline void S2C_Buy_Goods_Rsp::clear_has_cost_marbel() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void S2C_Buy_Goods_Rsp::clear_cost_marbel() {
  cost_marbel_ = 0;
  clear_has_cost_marbel();
}
inline ::google::protobuf::int32 S2C_Buy_Goods_Rsp::cost_marbel() const {
  return cost_marbel_;
}
inline void S2C_Buy_Goods_Rsp::set_cost_marbel(::google::protobuf::int32 value) {
  set_has_cost_marbel();
  cost_marbel_ = value;
}

// optional int32 cost_goldcoin = 4;
inline bool S2C_Buy_Goods_Rsp::has_cost_goldcoin() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void S2C_Buy_Goods_Rsp::set_has_cost_goldcoin() {
  _has_bits_[0] |= 0x00000008u;
}
inline void S2C_Buy_Goods_Rsp::clear_has_cost_goldcoin() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void S2C_Buy_Goods_Rsp::clear_cost_goldcoin() {
  cost_goldcoin_ = 0;
  clear_has_cost_goldcoin();
}
inline ::google::protobuf::int32 S2C_Buy_Goods_Rsp::cost_goldcoin() const {
  return cost_goldcoin_;
}
inline void S2C_Buy_Goods_Rsp::set_cost_goldcoin(::google::protobuf::int32 value) {
  set_has_cost_goldcoin();
  cost_goldcoin_ = value;
}

// repeated .DBCACHE.Prop gain_prop = 5;
inline int S2C_Buy_Goods_Rsp::gain_prop_size() const {
  return gain_prop_.size();
}
inline void S2C_Buy_Goods_Rsp::clear_gain_prop() {
  gain_prop_.Clear();
}
inline const ::DBCACHE::Prop& S2C_Buy_Goods_Rsp::gain_prop(int index) const {
  return gain_prop_.Get(index);
}
inline ::DBCACHE::Prop* S2C_Buy_Goods_Rsp::mutable_gain_prop(int index) {
  return gain_prop_.Mutable(index);
}
inline ::DBCACHE::Prop* S2C_Buy_Goods_Rsp::add_gain_prop() {
  return gain_prop_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::DBCACHE::Prop >&
S2C_Buy_Goods_Rsp::gain_prop() const {
  return gain_prop_;
}
inline ::google::protobuf::RepeatedPtrField< ::DBCACHE::Prop >*
S2C_Buy_Goods_Rsp::mutable_gain_prop() {
  return &gain_prop_;
}

// -------------------------------------------------------------------

// C2S_Present_Goods_Req

// required int32 goods_id = 1;
inline bool C2S_Present_Goods_Req::has_goods_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void C2S_Present_Goods_Req::set_has_goods_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void C2S_Present_Goods_Req::clear_has_goods_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void C2S_Present_Goods_Req::clear_goods_id() {
  goods_id_ = 0;
  clear_has_goods_id();
}
inline ::google::protobuf::int32 C2S_Present_Goods_Req::goods_id() const {
  return goods_id_;
}
inline void C2S_Present_Goods_Req::set_goods_id(::google::protobuf::int32 value) {
  set_has_goods_id();
  goods_id_ = value;
}

// repeated int32 receiver_id = 2;
inline int C2S_Present_Goods_Req::receiver_id_size() const {
  return receiver_id_.size();
}
inline void C2S_Present_Goods_Req::clear_receiver_id() {
  receiver_id_.Clear();
}
inline ::google::protobuf::int32 C2S_Present_Goods_Req::receiver_id(int index) const {
  return receiver_id_.Get(index);
}
inline void C2S_Present_Goods_Req::set_receiver_id(int index, ::google::protobuf::int32 value) {
  receiver_id_.Set(index, value);
}
inline void C2S_Present_Goods_Req::add_receiver_id(::google::protobuf::int32 value) {
  receiver_id_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
C2S_Present_Goods_Req::receiver_id() const {
  return receiver_id_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
C2S_Present_Goods_Req::mutable_receiver_id() {
  return &receiver_id_;
}

// -------------------------------------------------------------------

// S2C_Present_Goods_Rsp

// required int32 ret_code = 1;
inline bool S2C_Present_Goods_Rsp::has_ret_code() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void S2C_Present_Goods_Rsp::set_has_ret_code() {
  _has_bits_[0] |= 0x00000001u;
}
inline void S2C_Present_Goods_Rsp::clear_has_ret_code() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void S2C_Present_Goods_Rsp::clear_ret_code() {
  ret_code_ = 0;
  clear_has_ret_code();
}
inline ::google::protobuf::int32 S2C_Present_Goods_Rsp::ret_code() const {
  return ret_code_;
}
inline void S2C_Present_Goods_Rsp::set_ret_code(::google::protobuf::int32 value) {
  set_has_ret_code();
  ret_code_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace GAMESHOP

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_gameshop_2eproto__INCLUDED
